### ISSUE TITLE
d3.group convenience function?

### ISSUE THREAD

**Issue by mbostock** [d3/d3-collection#12]
Sometimes it’s convenient to group an array by a single key. You can do that using d3.nest like so:

```js
var entries = d3.nest()
    .key(d => d.foo)
    .entries(data);
```

Is it worth making a convenience function for this?

```js
d3.group = function(array, key) {
  return d3.nest().key(key).entries(array);
};
```

I guess it would violate the parsimony principle.

**Comment by geekplux** [comment]
d3.group is more semantic.

**Comment by 1wheel** [comment]
We've been using [nestBy](https://github.com/1wheel/d3-jetpack-module#nestBy)

```js
d3.nestBy = function(array, key){
  return d3.nest()
    .key(key)
    .entries(array)
    .map(function(d){
      d.values.key = d.key
      return d.values
    })
}
```

Not having to type `values` a zillion times is nice since I use them so much. I typically manually add multiple levels of nesting and mutate with a `forEach` loop instead of using `sort`, `rollup` or multiple `key` calls:

```js
var byCountry = d3.nestBy(data, d => d.country)
byCountry.forEach(d => {
  d.sort(d3.ascendingKey(d => d.year))
  d.byYear = d3.nestBy(d, d => d.year)
  d.byYear.forEach((year, i) => {
    var cumulativePercent = 0
    year.sort(d3.ascendingKey(d => d.isRight ? 0 : d.isCenter: 2 : 1))
      .forEach(d => {
        cumulativePercent += d.percent
        d.cumulativePercent = cumulativePercent
      })
  })
})
```

The ends up being a bit longer and not nearly as pretty, but is easier to incrementally experiment with different subgrouping and summary statistics while exploring different forms.

**Comment by mbostock** [comment]
Moving discussion over to d3/d3-array#75.
